#PYTHON에서 DFS를 사용할때 깊이가 깊어지면 오류를 발생시킬때가 있다. 아래의 line3 ~ 5를 사용하면 해결이다.

import sys
limit_number = 10000
sys.setrecursionlimit(limit_number)

def DFS(x, y, maps, visit):
    control = [[0, 1], [0, -1], [1, 0], [-1, 0]]
    answer = int(maps[x][y])
    visit[x][y] = 1
    
    for px, py in control:
        nx, ny = x+px, y+py
        if 0 <= nx < len(maps) and 0 <= ny < len(maps[0]):
            if maps[nx][ny] != 'X' and visit[nx][ny] == 0:
                answer += DFS(nx, ny, maps, visit)
                
    return answer

def solution(maps):
    answer = []
    visit = [[0 for _ in range(len(maps[0]))] for _ in range(len(maps))]
    
    for x in range(len(maps)):
        for y in range(len(maps[0])):
            if maps[x][y] != 'X' and visit[x][y] == 0:
                answer.append(DFS(x, y, maps, visit))
            
    
    return sorted(answer) if len(answer) else [-1]
